version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: swarshala
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  nodeapp:
    build: .
    container_name: nodeapp
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - sqlite_data:/usr/src/app/data
    ports:
      - "3000:3000"

volumes:
  mongo_data:
  sqlite_data:
